spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 347866
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.kanxz.movie: debug


mybatis-plus:
  mapper-locations:
    - classpath:generator/mapper/*.xml
    - classpath:mapper/*.xml
  configuration:
    cache-enabled: true